import { DiffOverview } from '@mortal-lens/types';
import { Meta, StoryObj } from '@storybook/react';

import { DiffOverviewTable } from '.';

const meta = {
  component: DiffOverviewTable,
  title: 'DiffOverviewTable',
  tags: ['autodocs'],
} satisfies Meta<typeof DiffOverviewTable>;

export default meta;
type Story = StoryObj<typeof meta>;

const oneJSONDiff = [
  {
    bakaze: 'E',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 3,
    aiProbability: 0.080927305,
    tags: ['suhai&suhai'],
    shanten: 4,
  },
  {
    bakaze: 'E',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 5,
    aiProbability: 0.29253003,
    tags: ['suhai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Critical',
    junme: 6,
    aiProbability: 0.012061284,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 11,
    aiProbability: 0.057050772,
    tags: ['suhai&suhai'],
    shanten: 1,
  },
  {
    bakaze: 'E',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Critical',
    junme: 12,
    aiProbability: 0.00257644,
    tags: ['jihai&suhai'],
    shanten: 1,
  },
  {
    bakaze: 'E',
    kyoku: 2,
    honba: 1,
    diffLevel: 'Optimal',
    junme: 1,
    aiProbability: 0.34570366,
    tags: ['jihai&suhai'],
    shanten: 4,
  },
  {
    bakaze: 'E',
    kyoku: 2,
    honba: 1,
    diffLevel: 'Optimal',
    junme: 2,
    aiProbability: 0.09244716,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 2,
    honba: 1,
    diffLevel: 'Optimal',
    junme: 5,
    aiProbability: 0.09333883,
    tags: ['jihai&suhai', 'myfuuro'],
    shanten: 2,
  },
  {
    bakaze: 'E',
    kyoku: 2,
    honba: 1,
    diffLevel: 'Critical',
    junme: 6,
    aiProbability: 0.029229743,
    tags: ['jihai&suhai', 'myfuuro'],
    shanten: 2,
  },
  {
    bakaze: 'E',
    kyoku: 2,
    honba: 1,
    diffLevel: 'Optimal',
    junme: 9,
    aiProbability: 0.22216082,
    tags: ['suhai&suhai', 'myfuuro'],
    shanten: 1,
  },
  {
    bakaze: 'E',
    kyoku: 2,
    honba: 1,
    diffLevel: 'Optimal',
    junme: 10,
    aiProbability: 0.06375719,
    tags: ['jihai&suhai', 'myfuuro'],
    shanten: 1,
  },
  {
    bakaze: 'E',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Critical',
    junme: 2,
    aiProbability: 0.0006469789,
    tags: ['jihai&jihai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Critical',
    junme: 3,
    aiProbability: 0.025068536,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Critical',
    junme: 6,
    aiProbability: 0.0000030431115,
    tags: ['jihai&suhai'],
    shanten: 2,
  },
  {
    bakaze: 'E',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 7,
    aiProbability: 0.2915882,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Critical',
    junme: 10,
    aiProbability: 0.0018427278,
    tags: ['jihai&suhai', 'myfuuro'],
    shanten: 1,
  },
  {
    bakaze: 'E',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Critical',
    junme: 12,
    aiProbability: 0.013843689,
    tags: ['jihai&suhai', 'myfuuro'],
    shanten: 1,
  },
  {
    bakaze: 'E',
    kyoku: 4,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 2,
    aiProbability: 0.18000095,
    tags: ['suhai&suhai'],
    shanten: 4,
  },
  {
    bakaze: 'E',
    kyoku: 4,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 4,
    aiProbability: 0.33164325,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'E',
    kyoku: 4,
    honba: 0,
    diffLevel: 'Critical',
    junme: 5,
    aiProbability: 0.028594268,
    tags: ['suhai&suhai'],
    shanten: 2,
  },
  {
    bakaze: 'E',
    kyoku: 4,
    honba: 0,
    diffLevel: 'Critical',
    junme: 6,
    aiProbability: 0.008108907,
    tags: ['suhai&suhai'],
    shanten: 2,
  },
  {
    bakaze: 'S',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 1,
    aiProbability: 0.38771614,
    tags: ['jihai&jihai'],
    shanten: 4,
  },
  {
    bakaze: 'S',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 3,
    aiProbability: 0.2719016,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 6,
    aiProbability: 0.3601617,
    tags: ['naki'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Critical',
    junme: 6,
    aiProbability: 0.010343482,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 1,
    honba: 0,
    diffLevel: 'Critical',
    junme: 8,
    aiProbability: 0.00043826932,
    tags: ['suhai&suhai', 'riichi_op'],
    shanten: 2,
  },
  {
    bakaze: 'S',
    kyoku: 2,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 0,
    aiProbability: 0.080951944,
    tags: ['jihai&suhai'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 2,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 2,
    aiProbability: 0.061239857,
    tags: ['suhai&suhai', 'myfuuro'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 2,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 9,
    aiProbability: 0.3040236,
    tags: ['jihai&suhai', 'myfuuro'],
    shanten: 1,
  },
  {
    bakaze: 'S',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 5,
    aiProbability: 0.23815972,
    tags: ['jihai&suhai', 'riichi_op'],
    shanten: 2,
  },
  {
    bakaze: 'S',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 8,
    aiProbability: 0.16821012,
    tags: ['suhai&suhai', 'riichi_op'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 3,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 9,
    aiProbability: 0.43335164,
    tags: ['suhai&suhai', 'riichi_op'],
    shanten: 3,
  },
  {
    bakaze: 'S',
    kyoku: 4,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 7,
    aiProbability: 0.37223074,
    tags: ['suhai&suhai'],
    shanten: 1,
  },
  {
    bakaze: 'S',
    kyoku: 4,
    honba: 0,
    diffLevel: 'Optimal',
    junme: 10,
    aiProbability: 0.14225255,
    tags: ['suhai&suhai', 'fuuro_op'],
    shanten: 1,
  },
] as DiffOverview[];

export const OneJSONDiff: Story = {
  args: {
    diff: oneJSONDiff,
  },
};
