import { Meta, StoryObj } from '@storybook/react';

import { KyokuDiff } from '@/types/output/RoundDiff';

import { KyokuSummary } from './KyokuSummary';

const meta = {
  component: KyokuSummary,
  title: 'KyokuSummary',
  tags: ['autodocs'],
} satisfies Meta<typeof KyokuSummary>;

export default meta;
type Story = StoryObj<typeof meta>;

const defaultArgs = [
  {
    kyoku: 0,
    honba: 0,
    junme: 3,
    shanten: 4,
    diffLevel: 'moderate',
    aiProbability: 8.09,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 0,
    honba: 0,
    junme: 5,
    shanten: 3,
    diffLevel: 'optimal',
    aiProbability: 29.25,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 0,
    honba: 0,
    junme: 6,
    shanten: 3,
    diffLevel: 'significant',
    aiProbability: 1.21,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 0,
    honba: 0,
    junme: 11,
    shanten: 1,
    diffLevel: 'moderate',
    aiProbability: 5.71,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 0,
    honba: 0,
    junme: 12,
    shanten: 1,
    diffLevel: 'significant',
    aiProbability: 0.26,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 1,
    honba: 1,
    junme: 2,
    shanten: 4,
    diffLevel: 'optimal',
    aiProbability: 34.57,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 1,
    honba: 1,
    junme: 3,
    shanten: 3,
    diffLevel: 'moderate',
    aiProbability: 9.24,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 1,
    honba: 1,
    junme: 6,
    shanten: 2,
    diffLevel: 'moderate',
    aiProbability: 9.33,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 1,
    honba: 1,
    junme: 7,
    shanten: 2,
    diffLevel: 'significant',
    aiProbability: 2.92,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 1,
    honba: 1,
    junme: 9,
    shanten: 1,
    diffLevel: 'moderate',
    aiProbability: 22.22,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 1,
    honba: 1,
    junme: 11,
    shanten: 1,
    diffLevel: 'moderate',
    aiProbability: 6.38,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 2,
    honba: 0,
    junme: 2,
    shanten: 3,
    diffLevel: 'significant',
    aiProbability: 0.06,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 2,
    honba: 0,
    junme: 3,
    shanten: 3,
    diffLevel: 'significant',
    aiProbability: 2.51,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 2,
    honba: 0,
    junme: 6,
    shanten: 2,
    diffLevel: 'critical',
    aiProbability: 0,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 2,
    honba: 0,
    junme: 7,
    shanten: 3,
    diffLevel: 'optimal',
    aiProbability: 29.16,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 2,
    honba: 0,
    junme: 10,
    shanten: 1,
    diffLevel: 'significant',
    aiProbability: 0.18,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 2,
    honba: 0,
    junme: 12,
    shanten: 1,
    diffLevel: 'significant',
    aiProbability: 1.38,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 3,
    honba: 0,
    junme: 2,
    shanten: 4,
    diffLevel: 'moderate',
    aiProbability: 18,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 3,
    honba: 0,
    junme: 4,
    shanten: 3,
    diffLevel: 'optimal',
    aiProbability: 33.16,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 3,
    honba: 0,
    junme: 5,
    shanten: 2,
    diffLevel: 'significant',
    aiProbability: 2.86,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 3,
    honba: 0,
    junme: 6,
    shanten: 2,
    diffLevel: 'significant',
    aiProbability: 0.81,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 4,
    honba: 0,
    junme: 1,
    shanten: 4,
    diffLevel: 'optimal',
    aiProbability: 38.77,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 4,
    honba: 0,
    junme: 3,
    shanten: 3,
    diffLevel: 'optimal',
    aiProbability: 27.19,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 4,
    honba: 0,
    junme: 5,
    shanten: 3,
    diffLevel: 'optimal',
    aiProbability: 36.02,
    tags: [],
  },
  {
    kyoku: 4,
    honba: 0,
    junme: 6,
    shanten: 3,
    diffLevel: 'significant',
    aiProbability: 1.03,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 4,
    honba: 0,
    junme: 8,
    shanten: 2,
    diffLevel: 'significant',
    aiProbability: 0.04,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 5,
    honba: 0,
    junme: 1,
    shanten: 3,
    diffLevel: 'moderate',
    aiProbability: 8.1,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 5,
    honba: 0,
    junme: 3,
    shanten: 3,
    diffLevel: 'moderate',
    aiProbability: 6.12,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 5,
    honba: 0,
    junme: 10,
    shanten: 1,
    diffLevel: 'optimal',
    aiProbability: 30.4,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 6,
    honba: 0,
    junme: 5,
    shanten: 2,
    diffLevel: 'moderate',
    aiProbability: 23.82,
    tags: ['jihai&jihai'],
  },
  {
    kyoku: 6,
    honba: 0,
    junme: 8,
    shanten: 3,
    diffLevel: 'moderate',
    aiProbability: 16.82,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 6,
    honba: 0,
    junme: 9,
    shanten: 3,
    diffLevel: 'optimal',
    aiProbability: 43.34,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 7,
    honba: 0,
    junme: 7,
    shanten: 1,
    diffLevel: 'optimal',
    aiProbability: 37.22,
    tags: ['jihai&suhai'],
  },
  {
    kyoku: 7,
    honba: 0,
    junme: 9,
    shanten: 1,
    diffLevel: 'moderate',
    aiProbability: 14.23,
    tags: ['jihai&suhai'],
  },
] as KyokuDiff[];

export const Default: Story = {
  args: {
    kyokuDiffs: defaultArgs,
  },
};
